import {analyze,ranks,RELATIONSHIP_CATEGORIES,METRICS,classifyCastTier} from './engine.js';
const $=s=>document.querySelector(s), app=$('#app');
const roleKo={TURNING_POINT:'인생 전환점',LIFELONG_ALLY:'평생 조력자',GROWTH_CATALYST:'성장 촉진자',RIVAL:'라이벌',SCENE_STEALER:'씬스틸러',HIDDEN_HELPER:'숨은 조력자',LONG_TERM_PRESENCE:'오래 남는 사람',STRONG_IMPRINT:'강렬한 흔적',WILDCARD:'변수',FINAL_BOSS:'최종보스',SLOW_BURN:'천천히 타오르는 사랑',MAIN_LEAD:'주연',SECOND_LEAD:'서브 주연',END_CREDIT_FRIEND:'엔딩 크레딧 친구',LOYAL_ALLY:'든든한 동료',LONG_TERM_CAST:'오래 함께할 캐스트',SHORT_BUT_STRONG:'짧고 강렬한 인연',POWER_DUO:'파워 듀오',BEST_PARTNER:'최고의 파트너',GROWTH_PARTNER:'성장 파트너',CATALYST:'촉매',MENTOR_ENERGY:'멘토 에너지',AWAKENER:'각성자'};
const tierKo={MAIN:'주연',SUPPORTING:'조연',FEATURED:'단역',CAMEO:'카메오'};
const relationshipGenreKo={ROMANCE:'로맨스',ROMANTIC_COMEDY:'로맨틱 코미디',MELODRAMA:'멜로',NOIR:'느와르',PSYCHOLOGICAL_THRILLER:'심리 스릴러',HEALING_DRAMA:'힐링 드라마',GROWTH_DRAMA:'성장 드라마',MYSTERY:'미스터리',FANTASY:'판타지'};
const genreKo={romance:'Romance',friendship:'Friendship',career:'Career',growth:'Growth'};
const sample=[['서윤','1997-04-18','08:20','FEMALE','MANUAL'],['민재','1995-11-02','unknown','MALE','INVITE'],['하린','1998-07-29','21:10','FEMALE','MANUAL'],['도윤','1994-02-14','13:30','MALE','INVITE']];
const owner={nickname:'유리',birthDate:'1996-08-15',birthTime:'10:30',gender:'FEMALE'};
function seed(){return sample.map((x,i)=>{const c={id:'c'+(i+1),nickname:x[0],birthDate:x[1],birthTime:x[2],gender:x[3],sourceType:x[4],createdAt:i+1};c.analysis=analyze(owner,c);return c})}
let state=JSON.parse(localStorage.getItem('reelation-state')||'null')||{onboarded:true,owner,cast:seed(),invite:true};
const save=()=>localStorage.setItem('reelation-state',JSON.stringify(state));
if(state.cast.some(c=>c.analysis?.scoringVersion!=='reelation-v2')){state.cast.forEach(c=>c.analysis=analyze(state.owner,c));save()}
const displayScore=value=>Math.round(Number(value));
const artIndex=c=>Math.abs([...String(c.id||c.nickname)].reduce((n,ch)=>n+ch.charCodeAt(0),0))%4;
const art=c=>`<div class="cast-art art-${artIndex(c)}" aria-hidden="true"></div>`;
function go(path){history.pushState({},'',path);render();scrollTo(0,0)} window.onpopstate=render;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
const role=r=>roleKo[r]||r.replaceAll('_',' ');
function layout(content,active='board'){app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand" data-go="/board">Reelation<span class="brand-dot">.</span></div><div class="avatar">${state.owner.nickname[0]}</div></header>${content}<nav class="bottomnav"><button class="navitem ${active==='board'?'active':''}" data-go="/board"><i>◫</i>Board</button><button class="navitem ${active==='cast'?'active':''}" data-go="/cast"><i>◎</i>Cast</button><button class="navitem ${active==='ranking'?'active':''}" data-go="/ranking"><i>↗</i>Ranking</button><button class="navitem ${active==='my'?'active':''}" data-go="/settings"><i>◉</i>My</button></nav></div>`;bind()}
function bind(){document.querySelectorAll('[data-go]').forEach(e=>e.onclick=()=>go(e.dataset.go))}
function board(){const cast=state.cast,ranked=ranks(cast,'overall'),cards=ranked.map(c=>{const tier=classifyCastTier(c.analysis.scores,c.rank,cast.length);return`<article class="casting-card tier-${tier.toLowerCase()}" data-go="/cast/${c.id}">${['MAIN','SUPPORTING'].includes(tier)?art(c):''}<span class="cast-tier">${tierKo[tier]}</span><div><b>${c.nickname}</b>${tier==='CAMEO'?'<small>★ SPECIAL APPEARANCE</small>':''}</div></article>`}).join('');layout(`<main class="page reel-page"><section class="movie-hero"><div class="movie-copy"><div class="eyebrow">01 · REELATION ORIGINAL</div><h1>「끝까지<br>장면을 바꾸는 사람」</h1><p class="movie-genre">성장 드라마 × 판타지</p><div class="main-character-copy"><span>MAIN CHARACTER</span><b>판을 뒤집는 성장형 주인공</b><p>사람과 사건을 거치며 자기만의 세계를 계속 확장하는 타입.</p></div><div class="actions"><button class="btn red" data-go="/cast/new">+ 출연진 추가</button><button class="btn alt" data-go="/invite">친구 초대</button></div></div><div class="movie-poster">${art({id:'owner-main'})}<span class="poster-stamp">STARRING</span><strong>${state.owner.nickname}</strong><small>현재 출연진 ${cast.length}명</small></div></section><section class="reel-section"><div class="section-head"><div><span class="eyebrow">02 · CASTING BOARD</span><h2>내 영화의 출연진</h2></div><span class="section-note">카드 크기 = 내 삶에서의 비중</span></div><div class="casting-stage"><article class="casting-card main-character">${art({id:'owner-main'})}<span class="cast-tier">MAIN CHARACTER</span><div><b>${state.owner.nickname}</b><small>THE PROTAGONIST</small></div></article>${cards}</div></section><section class="reel-section ranking-section"><div class="section-head"><div><span class="eyebrow">03 · INFLUENCE RANKING</span><h2>인생 영향도 랭킹</h2></div><span class="participant-count">총 ${cast.length}명 참여</span></div><p class="ranking-definition">주인공의 삶에 얼마나 큰 영향과 존재감을 갖는지를 나타내는 순위예요.</p>${cast.length?rankList(ranked):'<div class="notice">첫 번째 출연진을 초대해보세요.</div>'}</section></main>`,'board');bind()}
function rankList(list){return `<section class="rank-card">${list.map(c=>`<div class="rank-row" data-go="/cast/${c.id}"><span class="rank-num">${c.rank}</span>${art(c)}<div><b>${c.nickname}</b><div class="scorebar"><i style="width:${c.rankScore}%"></i></div></div><span class="role">인생 영향도</span><span class="score-big">${c.rankScore}</span></div>`).join('')}</section>`}
function castList(){layout(`<main class="page"><div class="eyebrow">Your ensemble</div><h1>출연진</h1><div class="section-head"><p class="sub">총 ${state.cast.length}명의 관계가 분석되었습니다.</p><button class="btn red" data-go="/cast/new">+ 새 출연진</button></div>${rankList(ranks(state.cast,'overall'))}</main>`,'cast');bind()}
function add(){layout(`<main class="page form-wrap"><button class="back" data-go="/cast">←</button><div class="eyebrow">New cast member</div><h1>새로운 배역은<br>누구인가요?</h1><div class="choice"><button class="active">직접 등록</button><button data-go="/invite">초대 링크 공유</button></div><form id="castform"><div class="field"><label>닉네임 *</label><input name="nickname" required placeholder="이름 또는 별명"></div><div class="field-row"><div class="field"><label>성별 *</label><select name="gender"><option value="FEMALE">여성</option><option value="MALE">남성</option></select></div><div class="field"><label>달력 *</label><select name="calendar"><option>양력</option><option>음력</option></select></div></div><div class="field"><label>생년월일 *</label><input type="date" name="birthDate" required max="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>출생 시간 (선택)</label><input type="time" name="birthTime"></div><button class="btn red submit">관계 분석하고 캐스팅하기</button></form></main>`,'cast');bind();$('#castform').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),c={id:'c'+Date.now(),nickname:f.get('nickname'),birthDate:f.get('birthDate'),birthTime:f.get('birthTime')||'unknown',gender:f.get('gender'),sourceType:'MANUAL',createdAt:Date.now()};c.analysis=analyze(state.owner,c);state.cast.push(c);save();toast('새 출연진의 분석이 완료됐어요');go('/cast/'+c.id)}}
function detail(id){const c=state.cast.find(x=>x.id===id);if(!c){layout('<main class="page empty"><h2>삭제되었거나 찾을 수 없는 출연진입니다.</h2><button class="btn" data-go="/cast">돌아가기</button></main>');return}const ranked=state.cast.length>=3?ranks(state.cast,'overall'):[],rank=ranked.find(x=>x.id===id)?.rank??null,tier=classifyCastTier(c.analysis.scores,rank,state.cast.length);layout(`<main class="page"><button class="back" data-go="/cast">←</button><section class="detail-hero"><div><div class="eyebrow">${relationshipGenreKo[c.analysis.relationshipGenre]}</div><h1>${c.nickname}</h1><p>${rank?'인생 영향도 · #'+rank:'랭킹은 3명부터 공개됩니다'}</p><p><b>${tierKo[tier]}</b> · ${role(c.analysis.lifeRole)}</p></div><div class="mega-score">${displayScore(c.analysis.scores.overall)}</div></section><div class="section-head"><h2>Filmography</h2><span class="eyebrow">4 category roles</span></div><section class="filmography">${RELATIONSHIP_CATEGORIES.map(g=>{const x=c.analysis.categoryResults[g],r=state.cast.length>=3?ranks(state.cast,g).find(v=>v.id===id).rank:'–';return`<article class="film"><span class="eyebrow">${genreKo[g]}</span><b>${role(x.role)}</b><span>${displayScore(x.score)} / #${r}</span></article>`}).join('')}</section><div class="section-head"><h2>Relationship stats</h2></div><section class="stats">${METRICS.map(m=>`<div class="stat"><b>${displayScore(c.analysis.scores[m])}</b><small>${m.toUpperCase()}</small></div>`).join('')}</section><div class="section-head"><h2>Director's note</h2></div><section class="narrative"><b>${c.nickname}은(는) 당신의 이야기에서 ${role(c.analysis.lifeRole)}입니다.</b><p>관계 영화의 장르는 ${relationshipGenreKo[c.analysis.relationshipGenre]}입니다. 함께 있을 때 드러나는 ${c.analysis.scores.impact>75?'강한 존재감과 변화의 힘':'잔잔하지만 오래 남는 리듬'}이 이 관계의 핵심이에요.</p></section><div class="section-head"><button class="btn alt danger" id="delete">출연진에서 삭제</button></div></main>`);bind();$('#delete').onclick=()=>{if(confirm(`${c.nickname}을(를) 출연진에서 삭제할까요?`)){state.cast=state.cast.filter(x=>x.id!==id);save();go('/cast')}}}
function ranking(){let type=new URLSearchParams(location.search).get('type')||'overall';const draw=()=>{layout(`<main class="page"><div class="eyebrow">The leaderboard</div><h1>Ranking</h1>${state.cast.length<3?'<div class="notice">출연진 3명 이상부터 순위가 공개됩니다.</div>':`<div class="tabs">${['overall',...RELATIONSHIP_CATEGORIES,...METRICS].map(t=>`<button class="tab ${t===type?'active':''}" data-type="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div>${rankList(ranks(state.cast,type))}`}</main>`,'ranking');bind();document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{type=b.dataset.type;history.replaceState({},'',`/ranking?type=${type}`);draw()})};draw()}
function genre(g){layout(`<main class="page"><button class="back" data-go="/board">←</button><div class="eyebrow">Genre casting</div><h1>${genreKo[g]||'Genre'}</h1><p class="sub">${g==='romance'?'설렘과 지속성이 만드는 관계의 온도':g==='friendship'?'안정감과 협력으로 이어지는 우정의 장면':g==='career'?'함께 성취하고 경쟁하는 일의 파트너십':'서로를 다음 장면으로 이끄는 변화의 힘'}</p>${state.cast.length>=3?rankList(ranks(state.cast,g)):'<div class="notice">출연진 3명 이상부터 장르 순위가 공개됩니다.</div>'}</main>`);bind()}
function invite(){const url=location.origin+'/invite/reel-'+btoa(state.owner.nickname).replaceAll('=','');layout(`<main class="page form-wrap"><button class="back" data-go="/board">←</button><div class="eyebrow">Open casting</div><h1>내 영화에<br>초대하기</h1><section class="invite-card"><h2>${state.invite?'초대 링크가 열려 있어요':'초대가 비활성화됐어요'}</h2><p>참여자가 직접 입력한 생년월일과 출생 시간은 나에게 공개되지 않습니다.</p><div class="invite-url">${url}</div><div class="actions"><button class="btn" id="copy">링크 복사</button><button class="btn alt" id="toggle">${state.invite?'초대 끄기':'초대 켜기'}</button></div></section></main>`);bind();$('#copy').onclick=async()=>{if(navigator.clipboard)await navigator.clipboard.writeText(url);toast('초대 링크를 복사했어요')};$('#toggle').onclick=()=>{state.invite=!state.invite;save();invite()}}
function settings(){layout(`<main class="page"><div class="eyebrow">Profile</div><h1>My</h1><section class="rank-card"><div class="rank-row"><div class="avatar">${state.owner.nickname[0]}</div><div><b>${state.owner.nickname}</b><div class="role">내 Reelation 보드의 감독</div></div><span></span><button class="btn alt" id="reset">데모 초기화</button></div></section></main>`,'my');bind();$('#reset').onclick=()=>{localStorage.removeItem('reelation-state');location.reload()}}
function render(){const p=location.pathname;if(p==='/'||p==='/board'||p.startsWith('/reel/'))board();else if(p==='/cast')castList();else if(p==='/cast/new')add();else if(p.startsWith('/cast/'))detail(p.split('/')[2]);else if(p==='/ranking')ranking();else if(p.startsWith('/genre/'))genre(p.split('/')[2]);else if(p==='/invite')invite();else if(p==='/settings')settings();else board()}
render();
