import {SCORING_CONFIG as C} from './scoring-config.js';
export const GENRES=['romance','friendship','career','growth'];
export const METRICS=['attraction','stability','impact','growth','longevity','cooperation','conflict'];
const ELEMENTS=['wood','fire','earth','metal','water'], BRANCH=['SIX_HARMONY','CLASH','PUNISHMENT','HARM','DESTRUCTION','HALF_HARMONY','SAME_BRANCH'], STEM=['STEM_COMBINATION','STEM_CLASH','STEM_SAME','STEM_GENERATION','STEM_CONTROL'];
const clamp=n=>Math.max(C.scoreRange.min,Math.min(C.scoreRange.max,n));
const hash=s=>[...String(s)].reduce((a,c)=>Math.imul(a^c.charCodeAt(0),16777619)>>>0,2166136261);
const weighted=(v,w)=>Object.entries(w).reduce((n,[k,x])=>n+(k==='inverseLongevity'?100-v.longevity:v[k])*x,0);

// 교체 가능한 결정론적 어댑터. 실제 만세력 구현체도 동일 결과 형태만 반환하면 된다.
export function calculateSaju(p){const seed=`${p.birthDate}|${p.birthTimeKnown===false?'unknown':p.birthTime||'unknown'}|${p.calendarType||'SOLAR'}|${p.gender}`,h=hash(seed);return{engineVersion:C.sajuEngineVersion,dayMasterElement:ELEMENTS[h%5],stemIndex:h%10,branchIndex:Math.floor(h/10)%12,elementDistribution:Object.fromEntries(ELEMENTS.map((e,i)=>[e,((h>>(i*3))&7)+1])),hourKnown:p.birthTimeKnown!==false&&p.birthTime&&p.birthTime!=='unknown',fingerprint:h}}
export function calculateRelationship(a,b){const d=(ELEMENTS.indexOf(b.dayMasterElement)-ELEMENTS.indexOf(a.dayMasterElement)+5)%5,dm=d===0?'SAME_ELEMENT':d===1?'GENERATES_OTHER':d===4?'GENERATED_BY_OTHER':d===2?'CONTROLS_OTHER':'CONTROLLED_BY_OTHER',h=hash(`${a.fingerprint}:${b.fingerprint}`),stem=STEM[h%STEM.length],branch=BRANCH[Math.floor(h/7)%BRANCH.length],delta=Math.abs(a.fingerprint%5-b.fingerprint%5),element=delta>=3?'STRONG_COMPLEMENT':delta>=2?'ELEMENT_COMPLEMENT':'ELEMENT_OVERLOAD';return{dayMasterRelation:dm,interactions:[{code:stem,weight:1},{code:branch,weight:C.dayBranchMultiplier},{code:element,weight:1}],featureCodes:[`DM_${dm}`,`DAY_BRANCH_${branch}`,element]}}
export function calculateScores(f){const s=Object.fromEntries(METRICS.map(k=>[k,C.baseScore])),apply=(m={},x=1)=>Object.entries(m).forEach(([k,v])=>s[k]+=v*x);apply(C.dayMasterModifiers[f.dayMasterRelation]);f.interactions.forEach(({code,weight=1})=>apply(C.relationModifiers[code],weight));s.growth+=s.conflict>C.growthConflictBonus.moderateMax?C.growthConflictBonus.high:s.conflict>C.growthConflictBonus.moderateMin?C.growthConflictBonus.moderate:0;Object.keys(s).forEach(k=>s[k]=clamp(s[k]));s.overall=clamp(weighted(s,C.genreWeights.overall));return s}
export function calculateGenreScores(s,f={featureCodes:[]}){return Object.fromEntries(GENRES.map(g=>{let n=weighted(s,C.genreWeights[g]);if(g==='career'&&s.conflict>=C.careerConflictPenalty.threshold)n-=C.careerConflictPenalty.amount;n=clamp(n);return[g,{score:n,role:genreRole(g,n,s,f)}]}))}
export function determineGlobalRole(s,g){const v={...s,romance:g.romance.score},c=Object.entries(C.roleRules).filter(([,r])=>r.eligible(v)).map(([role,r])=>({role,score:weighted(v,r.weights)}));return c.sort((a,b)=>b.score-a.score)[0]?.role||'ENSEMBLE_CAST'}
function genreRole(g,n,s){if(g==='romance')return s.longevity<=55&&s.impact>=65?'CAMEO':s.stability>=72&&s.longevity>=72?'MAIN_LEAD':s.stability>=65?'SLOW_BURN':'SECOND_LEAD';if(g==='friendship')return s.longevity>=82?'END_CREDIT_FRIEND':s.cooperation>=72?'LOYAL_ALLY':s.longevity>=62?'LONG_TERM_CAST':'SHORT_BUT_STRONG';if(g==='career')return s.conflict>=80?'FINAL_BOSS':s.conflict>=65?'RIVAL':n>=78?'POWER_DUO':s.growth>=70?'GROWTH_PARTNER':'BEST_PARTNER';return s.growth>=82&&s.impact>=75?'TURNING_POINT':s.cooperation>=75?'HIDDEN_HELPER':s.stability>=72?'MENTOR_ENERGY':n>=70?'CATALYST':'AWAKENER'}
export function analyze(owner,cast){const os=calculateSaju({...owner,birthTimeKnown:owner.birthTime!=='unknown'}),cs=calculateSaju({...cast,birthTimeKnown:cast.birthTime!=='unknown'}),f=calculateRelationship(os,cs),scores=calculateScores(f),genres=calculateGenreScores(scores,f);return{scores,genres,globalRole:determineGlobalRole(scores,genres),confidence:os.hourKnown&&cs.hourKnown?'HIGH':'STANDARD',featureCodes:[...f.featureCodes,...METRICS.filter(k=>scores[k]>=60).map(k=>`${k.toUpperCase()}_${scores[k]>=80?'VERY_HIGH':'HIGH'}`)],scoringVersion:C.version,sajuEngineVersion:C.sajuEngineVersion,version:C.version,status:'DONE'}}
export function scoreBand(n){return n<40?'LOW':n<60?'MEDIUM':n<80?'HIGH':'VERY_HIGH'}
export function ranks(cast,type){const get=c=>type==='overall'?c.analysis.scores.overall:type in c.analysis.genres?c.analysis.genres[type].score:c.analysis.scores[type];return[...cast].sort((a,b)=>get(b)-get(a)||a.createdAt-b.createdAt).map((c,i)=>({...c,rank:i+1,rankScoreRaw:get(c),rankScore:Math.round(get(c))}))}
