import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');
const sql=fs.readFileSync(new URL('./supabase/migrations/20260815052000_add_public_reel_view_mode.sql',import.meta.url),'utf8');
const invite=fs.readFileSync(new URL('./invite-integration.js',import.meta.url),'utf8');
test('reel route has an explicit owner visitor mode boundary',()=>{assert.match(app,/resolveViewMode/);assert.match(app,/mode===VIEW_MODE\.OWNER\?board\(\):visitorPage/)});
test('visitor shell does not use owner layout navigation',()=>{const body=app.match(/function visitorLayout[\s\S]*?function visitorPage/)?.[0]||'';assert.doesNotMatch(body,/bottomnav/);assert.doesNotMatch(body,/topbar/)});
test('public projection grants exclude private fields',()=>{assert.match(sql,/grant select\(public_id,owner_nickname,title,hero_image_key,cast_count\)/);assert.doesNotMatch(sql,/grant select\([^;]*(birth|genre|narrative|life_role)/i)});
test('public projection tables have RLS and explicit grants',()=>{assert.match(sql,/alter table public\.public_reels enable row level security/);assert.match(sql,/alter table public\.public_cast_entries enable row level security/);assert.match(sql,/revoke all on public\.public_reels,public\.public_cast_entries from anon,authenticated/) });
test('verified invite hydrates the visitor from public projections',()=>{assert.match(invite,/from\('public_reels'\)/);assert.match(invite,/from\('public_cast_entries'\)/);assert.match(invite,/inviteToken:token/);assert.match(app,/meta\.title/);assert.match(app,/meta\.posterImageKey/)});
test('visitor public metadata excludes private birth and analysis fields',()=>{const projection=invite.match(/const publicMeta=\{[^;]+/s)?.[0]||'';assert.doesNotMatch(projection,/birth|saju|narrative|lifeRole/i);assert.match(app,/escapePublic/)});
