import {SCORING_CONFIG as C} from './scoring-config.ts';
export const RELATIONSHIP_CATEGORIES=['romance','friendship','career','growth'];
export const RELATIONSHIP_GENRES=['ROMANCE','ROMANTIC_COMEDY','MELODRAMA','NOIR','PSYCHOLOGICAL_THRILLER','HEALING_DRAMA','GROWTH_DRAMA','MYSTERY','FANTASY'];
export const CAST_TIERS=['MAIN','SUPPORTING','FEATURED','CAMEO'];
export const LIFE_ROLES=['TURNING_POINT','LIFELONG_ALLY','GROWTH_CATALYST','RIVAL','SCENE_STEALER','HIDDEN_HELPER','LONG_TERM_PRESENCE','STRONG_IMPRINT','WILDCARD','FINAL_BOSS'];
export const METRICS=['attraction','stability','impact','growth','longevity','cooperation','conflict'];
const ELEMENTS=['wood','fire','earth','metal','water'], BRANCH=['SIX_HARMONY','CLASH','PUNISHMENT','HARM','DESTRUCTION','HALF_HARMONY','SAME_BRANCH'], STEM=['STEM_COMBINATION','STEM_CLASH','STEM_SAME','STEM_GENERATION','STEM_CONTROL'];
const clamp=n=>Math.max(C.scoreRange.min,Math.min(C.scoreRange.max,n));
const hash=s=>[...String(s)].reduce((a,c)=>Math.imul(a^c.charCodeAt(0),16777619)>>>0,2166136261);
const weighted=(v,w)=>Object.entries(w).reduce((n,[k,x])=>n+(k==='inverseLongevity'?100-v.longevity:v[k])*x,0);

const mod=(n,m)=>((n%m)+m)%m;
function gregorianJdn(date){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(date||'');if(!match)throw new Error('INVALID_BIRTH_DATE');const [,ys,ms,ds]=match,y=Number(ys),m=Number(ms),d=Number(ds),check=new Date(Date.UTC(y,m-1,d));if(check.getUTCFullYear()!==y||check.getUTCMonth()!==m-1||check.getUTCDate()!==d)throw new Error('INVALID_BIRTH_DATE');const a=Math.floor((14-m)/12),yy=y+4800-a,mm=m+12*a-3;return d+Math.floor((153*mm+2)/5)+365*yy+Math.floor(yy/4)-Math.floor(yy/100)+Math.floor(yy/400)-32045}
const lunarFormatter=new Intl.DateTimeFormat('en-u-ca-chinese',{year:'numeric',month:'numeric',day:'numeric',timeZone:'Asia/Seoul'});
export function lunarToSolar(date){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(date||'');if(!match)throw new Error('INVALID_BIRTH_DATE');const targetYear=Number(match[1]),targetMonth=Number(match[2]),targetDay=Number(match[3]);for(let cursor=new Date(Date.UTC(targetYear,0,1,3));cursor<=new Date(Date.UTC(targetYear+1,2,31,3));cursor.setUTCDate(cursor.getUTCDate()+1)){const parts=Object.fromEntries(lunarFormatter.formatToParts(cursor).map(part=>[part.type,part.value])),month=String(parts.month||'');if(Number(parts.relatedYear||parts.year)===targetYear&&Number.parseInt(month,10)===targetMonth&&!month.includes('bis')&&Number(parts.day)===targetDay)return cursor.toISOString().slice(0,10)}throw new Error('INVALID_LUNAR_DATE')}
export function normalizeBirthDate(profile){if((profile.calendarType||'SOLAR')==='SOLAR')return profile;if(profile.calendarType!=='LUNAR')throw new Error('INVALID_CALENDAR_TYPE');return{...profile,originalBirthDate:profile.birthDate,originalCalendarType:'LUNAR',birthDate:lunarToSolar(profile.birthDate),calendarType:'SOLAR'}}
// Gregorian civil date at local midnight. JDN + 49 maps 2000-01-07 to 갑자(0).
export function calculateSaju(input){const p=normalizeBirthDate(input),dayPillarIndex=mod(gregorianJdn(p.birthDate)+49,60),dayStemIndex=dayPillarIndex%10,dayBranchIndex=dayPillarIndex%12,seed=`${p.birthDate}|${p.birthTimeKnown===false?'unknown':p.birthTime||'unknown'}|SOLAR|${p.gender}`,h=hash(seed);return{engineVersion:C.sajuEngineVersion,dayMasterElement:ELEMENTS[Math.floor(dayStemIndex/2)],stemIndex:dayStemIndex,branchIndex:dayBranchIndex,dayPillarIndex,dayStemIndex,dayBranchIndex,elementDistribution:Object.fromEntries(ELEMENTS.map((e,i)=>[e,((h>>(i*3))&7)+1])),hourKnown:p.birthTimeKnown!==false&&p.birthTime&&p.birthTime!=='unknown',fingerprint:h}}
export function calculateRelationship(a,b){const d=(ELEMENTS.indexOf(b.dayMasterElement)-ELEMENTS.indexOf(a.dayMasterElement)+5)%5,dm=d===0?'SAME_ELEMENT':d===1?'GENERATES_OTHER':d===4?'GENERATED_BY_OTHER':d===2?'CONTROLS_OTHER':'CONTROLLED_BY_OTHER',h=hash(`${a.fingerprint}:${b.fingerprint}`),stem=STEM[h%STEM.length],branch=BRANCH[Math.floor(h/7)%BRANCH.length],delta=Math.abs(a.fingerprint%5-b.fingerprint%5),element=delta>=3?'STRONG_COMPLEMENT':delta>=2?'ELEMENT_COMPLEMENT':'ELEMENT_OVERLOAD';return{dayMasterRelation:dm,interactions:[{code:stem,weight:1},{code:branch,weight:C.dayBranchMultiplier},{code:element,weight:1}],featureCodes:[`DM_${dm}`,`DAY_BRANCH_${branch}`,element]}}
export function calculateScores(f){const s=Object.fromEntries(METRICS.map(k=>[k,C.baseScore])),apply=(m={},x=1)=>Object.entries(m).forEach(([k,v])=>s[k]+=v*x);apply(C.dayMasterModifiers[f.dayMasterRelation]);f.interactions.forEach(({code,weight=1})=>apply(C.relationModifiers[code],weight));s.growth+=s.conflict>C.growthConflictBonus.moderateMax?C.growthConflictBonus.high:s.conflict>C.growthConflictBonus.moderateMin?C.growthConflictBonus.moderate:0;Object.keys(s).forEach(k=>s[k]=clamp(s[k]));s.overall=clamp(weighted(s,C.genreWeights.overall));return s}
export function calculateCategoryScores(s,f={featureCodes:[]}){return Object.fromEntries(RELATIONSHIP_CATEGORIES.map(g=>{let n=weighted(s,C.genreWeights[g]);if(g==='career'&&s.conflict>=C.careerConflictPenalty.threshold)n-=C.careerConflictPenalty.amount;n=clamp(n);return[g,{score:n,role:genreRole(g,n,s,f)}]}))}
export const calculateGenreScores=calculateCategoryScores;
export function determineLifeRole(s){const candidates=Object.entries(C.roleRules).filter(([,r])=>r.eligible(s)).map(([lifeRole,r])=>({lifeRole,score:weighted(s,r.weights)}));return candidates.sort((a,b)=>b.score-a.score)[0]?.lifeRole||'GROWTH_CATALYST'}
export const determineGlobalRole=(s)=>determineLifeRole(s);
export function determineRelationshipGenre(s,f={featureCodes:[]}){if(s.conflict>=78&&s.impact>=75&&s.stability<58)return'PSYCHOLOGICAL_THRILLER';if(s.attraction>=68&&s.impact>=70&&s.conflict>=62&&s.stability<68)return'NOIR';if(s.stability>=70&&s.longevity>=68&&s.cooperation>=65&&s.conflict<62)return'HEALING_DRAMA';if(s.growth>=76&&s.impact>=65)return'GROWTH_DRAMA';if(s.attraction>=70&&s.impact>=72&&s.conflict>=48)return'MELODRAMA';if(s.attraction>=66&&s.conflict>=38&&s.conflict<68&&s.stability>=56)return'ROMANTIC_COMEDY';if(s.attraction>=68&&s.stability>=62&&s.longevity>=60)return'ROMANCE';if(f.featureCodes?.some(x=>x.includes('STRONG_COMPLEMENT'))&&s.impact>=65)return'FANTASY';return'MYSTERY'}
export function classifyCastTier(s,relativeRank=null,castCount=0){if(s.impact>=75&&s.longevity<=50)return'CAMEO';const topBand=relativeRank&&castCount>=3&&relativeRank<=Math.max(1,Math.ceil(castCount*.25));if((s.overall>=70&&s.impact>=62&&s.longevity>=58)||(topBand&&s.overall>=62))return'MAIN';if(s.overall>=57||Math.max(s.attraction,s.stability,s.impact,s.growth,s.longevity,s.cooperation)>=72)return'SUPPORTING';return'FEATURED'}
function genreRole(g,n,s){if(g==='romance')return s.longevity<=55&&s.impact>=65?'SHORT_BUT_STRONG':s.stability>=72&&s.longevity>=72?'MAIN_LEAD':s.stability>=65?'SLOW_BURN':'SECOND_LEAD';if(g==='friendship')return s.longevity>=82?'END_CREDIT_FRIEND':s.cooperation>=72?'LOYAL_ALLY':s.longevity>=62?'LONG_TERM_CAST':'SHORT_BUT_STRONG';if(g==='career')return s.conflict>=80?'FINAL_BOSS':s.conflict>=65?'RIVAL':n>=78?'POWER_DUO':s.growth>=70?'GROWTH_PARTNER':'BEST_PARTNER';return s.growth>=82&&s.impact>=75?'TURNING_POINT':s.cooperation>=75?'HIDDEN_HELPER':s.stability>=72?'MENTOR_ENERGY':n>=70?'CATALYST':'AWAKENER'}
export function analyze(owner,cast){const os=calculateSaju({...owner,birthTimeKnown:owner.birthTime!=='unknown'}),cs=calculateSaju({...cast,birthTimeKnown:cast.birthTime!=='unknown'}),f=calculateRelationship(os,cs),scores=calculateScores(f),categoryResults=calculateCategoryScores(scores,f);return{scores,categoryResults,castTier:classifyCastTier(scores),lifeRole:determineLifeRole(scores),relationshipGenre:determineRelationshipGenre(scores,f),character:{dayPillarIndex:cs.dayPillarIndex,stemIndex:cs.dayStemIndex,branchIndex:cs.dayBranchIndex},confidence:os.hourKnown&&cs.hourKnown?'HIGH':'STANDARD',featureCodes:[...f.featureCodes,...METRICS.filter(k=>scores[k]>=60).map(k=>`${k.toUpperCase()}_${scores[k]>=80?'VERY_HIGH':'HIGH'}`)],scoringVersion:C.version,sajuEngineVersion:C.sajuEngineVersion,version:C.version,status:'DONE'}}
export function scoreBand(n){return n<40?'LOW':n<60?'MEDIUM':n<80?'HIGH':'VERY_HIGH'}
export function ranks(cast,type){const get=c=>type==='overall'?c.analysis.scores.overall:type in c.analysis.categoryResults?c.analysis.categoryResults[type].score:c.analysis.scores[type];return[...cast].sort((a,b)=>get(b)-get(a)||a.createdAt-b.createdAt).map((c,i)=>({...c,rank:i+1,rankScoreRaw:get(c),rankScore:Math.round(get(c))}))}
